'use strict';

/**
 * WhatsApp text formatting utilities.
 *
 * WhatsApp supports ONLY this subset of formatting:
 *   *bold*           (single asterisk, NOT double)
 *   _italic_         (single underscore)
 *   ~strikethrough~
 *   `inline code`    (single backtick)
 *   ```code block``` (triple backtick)
 *
 * Standard Markdown that DOES NOT render in WhatsApp:
 *   # / ## / ### headings   → shown literally
 *   **bold**                → shown literally (use *bold* instead)
 *   __bold__                → shown literally
 *   [text](url)             → shown literally
 *   ---                     → shown literally (no horizontal rule)
 *
 * GPT tends to emit standard Markdown by default, so anything generated by
 * the LLM needs to pass through `markdownToWhatsApp()` before we send it.
 */

const WHATSAPP_DIVIDER = '─'.repeat(20);

/**
 * Convert GPT / standard-Markdown text into WhatsApp-flavored formatting.
 *
 * Transformations applied:
 *   1. ATX headings (# / ## / ###) → WhatsApp bold *heading*
 *   2. ***bold italic*** → *_text_*
 *   3. **bold** → *bold*
 *   4. __bold__ → *bold*
 *   5. Horizontal rules (---, ***, ___) → unicode box-drawing line
 *   6. Leading "* item" bullets → "- item" (WhatsApp would treat `*` as bold)
 *   7. Markdown links [text](url) → "text (url)"
 *
 * Pure function — no side effects, safe on any string input.
 *
 * @param {unknown} md - Text to convert. Non-strings returned as-is.
 * @returns {string} WhatsApp-safe formatted text.
 */
function markdownToWhatsApp(md) {
  if (md == null || typeof md !== 'string' || md.length === 0) return md;

  let s = md;

  // IMPORTANT: use [ \t] (not \s) for INLINE whitespace in per-line rules so
  // we don't accidentally consume blank lines / newlines — \s would eat them
  // and collapse the message into one block.

  // 1. ATX headings ("# Title", "## Title", etc.) → WhatsApp bold.
  //    Removes the `#` prefix and wraps the heading text in `*...*`.
  s = s.replace(/^[ \t]{0,3}#{1,6}[ \t]+(.+?)[ \t]*#*[ \t]*$/gm, '*$1*');

  // 2. Triple-asterisk bold italic: ***text*** → *_text_*
  //    Must come BEFORE the `**...**` rule so we don't accidentally break it up.
  s = s.replace(/\*\*\*([^*\n][^*]*?[^*\n]|\S)\*\*\*/g, '*_$1_*');

  // 3. Double-asterisk bold: **text** → *text*
  s = s.replace(/\*\*([^*\n][^*]*?[^*\n]|\S)\*\*/g, '*$1*');

  // 4. Double-underscore bold: __text__ → *text*
  //    Single `_word_` stays as italic (WhatsApp supports it natively).
  s = s.replace(/__([^_\n]+?)__/g, '*$1*');

  // 5. Horizontal rules on their own line → unicode divider.
  s = s.replace(/^[ \t]*(?:[-*_][ \t]*){3,}[ \t]*$/gm, WHATSAPP_DIVIDER);

  // 6. Leading "* item" bullets at line start → "- item".
  //    Without this, WhatsApp's parser tries to treat the leading `*` as bold
  //    and swallows formatting across lines.
  s = s.replace(/^([ \t]*)\*[ \t]+(?=\S)/gm, '$1- ');

  // 7. Markdown links: [text](url) → "text (url)". Keep URL visible so users
  //    can tap it — WhatsApp auto-links bare URLs.
  s = s.replace(/\[([^\]]+)\]\(([^)\s]+)\)/g, '$1 ($2)');

  return s;
}

module.exports = {
  markdownToWhatsApp,
  WHATSAPP_DIVIDER,
};
